#!/usr/bin/env bash
# Writes infrastructure/.env for LAN access (CORS, Kafka, APP_URL).
set -euo pipefail
cd "$(dirname "$0")"

# Prefer the IP used for the default route (real LAN). Skip Docker/WSL bridge ranges
# that hostname -I often lists first and that break Kafka advertised listeners.
is_bad_ip() {
  case "$1" in
    172.1[6-9].*|172.2[0-9].*|172.3[0-1].*|172.17.*|172.18.*|127.*|::1|169.254.*) return 0 ;;
    *) return 1 ;;
  esac
}

detect_lan_host() {
  local ip=""
  # Default-route source address (most reliable)
  ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' || true)"
  if [[ -n "${ip}" ]] && ! is_bad_ip "${ip}"; then
    echo "${ip}"
    return 0
  fi
  # Fall back to first non-docker global address
  while read -r cand; do
    if [[ -n "${cand}" ]] && ! is_bad_ip "${cand}"; then
      echo "${cand}"
      return 0
    fi
  done < <(hostname -I 2>/dev/null | tr ' ' '\n')
  return 1
}

if [[ -n "${LAN_HOST:-}" ]]; then
  :
elif LAN_HOST="$(detect_lan_host)"; then
  :
else
  echo "Could not detect a usable LAN IP. Set LAN_HOST and re-run, e.g.:" >&2
  echo "  LAN_HOST=192.168.1.42 $0" >&2
  echo "  LAN_HOST=localhost $0   # local-only (no phone/LAN clients)" >&2
  exit 1
fi

cat > .env <<EOF
# Generated by setup-network-env.sh — safe to edit
# Kafka advertises PLAINTEXT://\${LAN_HOST}:9092 — this MUST be reachable from
# host-run services (file-service, etc.). Use localhost for same-machine-only,
# or your current Wi‑Fi/Ethernet IP for LAN access. Stale IPs cause Connection timeout.
LAN_HOST=${LAN_HOST}
CORS_ORIGIN=http://${LAN_HOST}:5173,http://localhost:5173
APP_URL=http://${LAN_HOST}:5173
EOF

echo "Wrote infrastructure/.env (LAN_HOST=${LAN_HOST})"
echo "  CORS_ORIGIN=http://${LAN_HOST}:5173,http://localhost:5173"
echo "  APP_URL=http://${LAN_HOST}:5173"
echo ""
echo "Next:"
echo "  cd infrastructure && docker compose up -d --force-recreate kafka"
echo "  In client/.env: VITE_API_URL=http://${LAN_HOST}:3000"
echo "  In client: npm run dev -- --host"
