#!/usr/bin/env bash
# Writes infrastructure/.env for LAN access (CORS, Kafka, APP_URL).
set -euo pipefail
cd "$(dirname "$0")"

LAN_HOST="${LAN_HOST:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
if [[ -z "${LAN_HOST}" ]]; then
  echo "Could not detect LAN IP. Set LAN_HOST and re-run, e.g.: LAN_HOST=192.168.1.42 $0" >&2
  exit 1
fi

cat > .env <<EOF
# Generated by setup-network-env.sh — safe to edit
LAN_HOST=${LAN_HOST}
CORS_ORIGIN=http://${LAN_HOST}:5173,http://localhost:5173
APP_URL=http://${LAN_HOST}:5173
EOF

echo "Wrote infrastructure/.env (LAN_HOST=${LAN_HOST})"
echo "  CORS_ORIGIN=http://${LAN_HOST}:5173,http://localhost:5173"
echo "  APP_URL=http://${LAN_HOST}:5173"
echo ""
echo "Next:"
echo "  cd infrastructure && docker compose up -d"
echo "  In client/.env: VITE_API_URL=http://${LAN_HOST}:3000"
echo "  In client: npm run dev -- --host"
